import "./globals.css";
import { Space_Grotesk } from "next/font/google";
import { ToastContainer } from "react-toastify"
import "react-toastify/dist/ReactToastify.css"
// ❌ REMOVED: Cron job should not be imported here - causes multiple instances
import GlobalProvider from "@/components/Application/GlobalProvider";
import ChatWidget from "@/components/Chatbot/ChatWidget";
import { getServerSession } from "@/lib/serverSession";

const spaceGrotesk = Space_Grotesk({
  weight: ["400", "500", "600", "700"],
  subsets: ["latin"],
  display: "swap",
  variable: "--font-space-grotesk"
})

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  // ✅ Server-side session check - happens BEFORE rendering
  const session = await getServerSession();

  return (
    <html lang="en">
      <body
        className={`${spaceGrotesk.variable} ${spaceGrotesk.className} antialiased`}
      >
        <GlobalProvider initialSession={session}>
          {children}
          <ToastContainer />
          <ChatWidget />
        </GlobalProvider>
      </body>
    </html>
  );
}

